/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as xulSwapFactorySol from "./XULSwapFactory.sol";
export type { xulSwapFactorySol };
export type { WBTC } from "./WBTC";
export type { WETH } from "./WETH";
export type { WUSDC } from "./WUSDC";
export type { WUSDT } from "./WUSDT";
export type { WXUL } from "./WXUL";
export type { X402PaymentProcessor } from "./X402PaymentProcessor";
export type { XULSwapRouter } from "./XULSwapRouter";
