/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace X402PaymentProcessor {
  export type PaymentAuthorizationStruct = {
    from: AddressLike;
    to: AddressLike;
    value: BigNumberish;
    validAfter: BigNumberish;
    validBefore: BigNumberish;
    nonce: BytesLike;
  };

  export type PaymentAuthorizationStructOutput = [
    from: string,
    to: string,
    value: bigint,
    validAfter: bigint,
    validBefore: bigint,
    nonce: string
  ] & {
    from: string;
    to: string;
    value: bigint;
    validAfter: bigint;
    validBefore: bigint;
    nonce: string;
  };
}

export interface X402PaymentProcessorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "NATIVE_TOKEN"
      | "acceptedTokens"
      | "addAcceptedToken"
      | "authorizeFacilitator"
      | "authorizedFacilitators"
      | "deauthorizeFacilitator"
      | "isPaymentValid"
      | "owner"
      | "removeAcceptedToken"
      | "renounceOwnership"
      | "settlePayment"
      | "transferOwnership"
      | "usedNonces"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FacilitatorAuthorized"
      | "FacilitatorDeauthorized"
      | "OwnershipTransferred"
      | "PaymentSettled"
      | "TokenAdded"
      | "TokenRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "NATIVE_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addAcceptedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeFacilitator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedFacilitators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deauthorizeFacilitator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPaymentValid",
    values: [
      AddressLike,
      X402PaymentProcessor.PaymentAuthorizationStruct,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeAcceptedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "settlePayment",
    values: [
      AddressLike,
      X402PaymentProcessor.PaymentAuthorizationStruct,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedNonces",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "NATIVE_TOKEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAcceptedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeFacilitator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedFacilitators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deauthorizeFacilitator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPaymentValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAcceptedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usedNonces", data: BytesLike): Result;
}

export namespace FacilitatorAuthorizedEvent {
  export type InputTuple = [facilitator: AddressLike];
  export type OutputTuple = [facilitator: string];
  export interface OutputObject {
    facilitator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FacilitatorDeauthorizedEvent {
  export type InputTuple = [facilitator: AddressLike];
  export type OutputTuple = [facilitator: string];
  export interface OutputObject {
    facilitator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentSettledEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    nonce: BytesLike,
    token: AddressLike
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    nonce: string,
    token: string
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    nonce: string;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenAddedEvent {
  export type InputTuple = [token: AddressLike];
  export type OutputTuple = [token: string];
  export interface OutputObject {
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenRemovedEvent {
  export type InputTuple = [token: AddressLike];
  export type OutputTuple = [token: string];
  export interface OutputObject {
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface X402PaymentProcessor extends BaseContract {
  connect(runner?: ContractRunner | null): X402PaymentProcessor;
  waitForDeployment(): Promise<this>;

  interface: X402PaymentProcessorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  NATIVE_TOKEN: TypedContractMethod<[], [string], "view">;

  acceptedTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  addAcceptedToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizeFacilitator: TypedContractMethod<
    [facilitator: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedFacilitators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  deauthorizeFacilitator: TypedContractMethod<
    [facilitator: AddressLike],
    [void],
    "nonpayable"
  >;

  isPaymentValid: TypedContractMethod<
    [
      token: AddressLike,
      auth: X402PaymentProcessor.PaymentAuthorizationStruct,
      signature: BytesLike
    ],
    [[boolean, string]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeAcceptedToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  settlePayment: TypedContractMethod<
    [
      token: AddressLike,
      auth: X402PaymentProcessor.PaymentAuthorizationStruct,
      signature: BytesLike
    ],
    [void],
    "payable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usedNonces: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "NATIVE_TOKEN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "addAcceptedToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizeFacilitator"
  ): TypedContractMethod<[facilitator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedFacilitators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deauthorizeFacilitator"
  ): TypedContractMethod<[facilitator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isPaymentValid"
  ): TypedContractMethod<
    [
      token: AddressLike,
      auth: X402PaymentProcessor.PaymentAuthorizationStruct,
      signature: BytesLike
    ],
    [[boolean, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeAcceptedToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settlePayment"
  ): TypedContractMethod<
    [
      token: AddressLike,
      auth: X402PaymentProcessor.PaymentAuthorizationStruct,
      signature: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedNonces"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "FacilitatorAuthorized"
  ): TypedContractEvent<
    FacilitatorAuthorizedEvent.InputTuple,
    FacilitatorAuthorizedEvent.OutputTuple,
    FacilitatorAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "FacilitatorDeauthorized"
  ): TypedContractEvent<
    FacilitatorDeauthorizedEvent.InputTuple,
    FacilitatorDeauthorizedEvent.OutputTuple,
    FacilitatorDeauthorizedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentSettled"
  ): TypedContractEvent<
    PaymentSettledEvent.InputTuple,
    PaymentSettledEvent.OutputTuple,
    PaymentSettledEvent.OutputObject
  >;
  getEvent(
    key: "TokenAdded"
  ): TypedContractEvent<
    TokenAddedEvent.InputTuple,
    TokenAddedEvent.OutputTuple,
    TokenAddedEvent.OutputObject
  >;
  getEvent(
    key: "TokenRemoved"
  ): TypedContractEvent<
    TokenRemovedEvent.InputTuple,
    TokenRemovedEvent.OutputTuple,
    TokenRemovedEvent.OutputObject
  >;

  filters: {
    "FacilitatorAuthorized(address)": TypedContractEvent<
      FacilitatorAuthorizedEvent.InputTuple,
      FacilitatorAuthorizedEvent.OutputTuple,
      FacilitatorAuthorizedEvent.OutputObject
    >;
    FacilitatorAuthorized: TypedContractEvent<
      FacilitatorAuthorizedEvent.InputTuple,
      FacilitatorAuthorizedEvent.OutputTuple,
      FacilitatorAuthorizedEvent.OutputObject
    >;

    "FacilitatorDeauthorized(address)": TypedContractEvent<
      FacilitatorDeauthorizedEvent.InputTuple,
      FacilitatorDeauthorizedEvent.OutputTuple,
      FacilitatorDeauthorizedEvent.OutputObject
    >;
    FacilitatorDeauthorized: TypedContractEvent<
      FacilitatorDeauthorizedEvent.InputTuple,
      FacilitatorDeauthorizedEvent.OutputTuple,
      FacilitatorDeauthorizedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentSettled(address,address,uint256,bytes32,address)": TypedContractEvent<
      PaymentSettledEvent.InputTuple,
      PaymentSettledEvent.OutputTuple,
      PaymentSettledEvent.OutputObject
    >;
    PaymentSettled: TypedContractEvent<
      PaymentSettledEvent.InputTuple,
      PaymentSettledEvent.OutputTuple,
      PaymentSettledEvent.OutputObject
    >;

    "TokenAdded(address)": TypedContractEvent<
      TokenAddedEvent.InputTuple,
      TokenAddedEvent.OutputTuple,
      TokenAddedEvent.OutputObject
    >;
    TokenAdded: TypedContractEvent<
      TokenAddedEvent.InputTuple,
      TokenAddedEvent.OutputTuple,
      TokenAddedEvent.OutputObject
    >;

    "TokenRemoved(address)": TypedContractEvent<
      TokenRemovedEvent.InputTuple,
      TokenRemovedEvent.OutputTuple,
      TokenRemovedEvent.OutputObject
    >;
    TokenRemoved: TypedContractEvent<
      TokenRemovedEvent.InputTuple,
      TokenRemovedEvent.OutputTuple,
      TokenRemovedEvent.OutputObject
    >;
  };
}
