/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace XULTranslator {
  export type AIModelStruct = {
    name: string;
    version: string;
    accuracy: BigNumberish;
    isActive: boolean;
  };

  export type AIModelStructOutput = [
    name: string,
    version: string,
    accuracy: bigint,
    isActive: boolean
  ] & { name: string; version: string; accuracy: bigint; isActive: boolean };

  export type TranslationRequestStruct = {
    id: BigNumberish;
    requester: AddressLike;
    sourceText: string;
    sourceLang: BigNumberish;
    targetLang: BigNumberish;
    reward: BigNumberish;
    deadline: BigNumberish;
    status: BigNumberish;
    translation: string;
    translator: AddressLike;
    qualityScore: BigNumberish;
    aiProof: BytesLike;
  };

  export type TranslationRequestStructOutput = [
    id: bigint,
    requester: string,
    sourceText: string,
    sourceLang: bigint,
    targetLang: bigint,
    reward: bigint,
    deadline: bigint,
    status: bigint,
    translation: string,
    translator: string,
    qualityScore: bigint,
    aiProof: string
  ] & {
    id: bigint;
    requester: string;
    sourceText: string;
    sourceLang: bigint;
    targetLang: bigint;
    reward: bigint;
    deadline: bigint;
    status: bigint;
    translation: string;
    translator: string;
    qualityScore: bigint;
    aiProof: string;
  };

  export type TranslatorStruct = {
    wallet: AddressLike;
    reputation: BigNumberish;
    completedJobs: BigNumberish;
    totalEarned: BigNumberish;
    specialties: BigNumberish[];
    isVerified: boolean;
    isActive: boolean;
  };

  export type TranslatorStructOutput = [
    wallet: string,
    reputation: bigint,
    completedJobs: bigint,
    totalEarned: bigint,
    specialties: bigint[],
    isVerified: boolean,
    isActive: boolean
  ] & {
    wallet: string;
    reputation: bigint;
    completedJobs: bigint;
    totalEarned: bigint;
    specialties: bigint[];
    isVerified: boolean;
    isActive: boolean;
  };
}

export interface XULTranslatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAIModel"
      | "addAIVerifier"
      | "aiModels"
      | "aiTranslate"
      | "aiVerifiers"
      | "disputeTranslation"
      | "getAIModels"
      | "getLanguageName"
      | "getRequest"
      | "getTranslator"
      | "minReward"
      | "owner"
      | "platformFee"
      | "registerTranslator"
      | "renounceOwnership"
      | "requestTranslation"
      | "requests"
      | "resolveDispute"
      | "rewardToken"
      | "setMinReward"
      | "setPlatformFee"
      | "submitTranslation"
      | "totalVolume"
      | "transferOwnership"
      | "translators"
      | "verifyTranslation"
      | "verifyTranslator"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "RewardDistributed"
      | "TranslationRequested"
      | "TranslationSubmitted"
      | "TranslationVerified"
      | "TranslatorRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAIModel",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addAIVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "aiModels",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "aiTranslate",
    values: [BigNumberish, string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "aiVerifiers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeTranslation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAIModels",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLanguageName",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTranslator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "minReward", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerTranslator",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestTranslation",
    values: [string, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMinReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitTranslation",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalVolume",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "translators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyTranslation",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyTranslator",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "addAIModel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addAIVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "aiModels", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "aiTranslate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aiVerifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeTranslation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAIModels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLanguageName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRequest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTranslator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "minReward", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerTranslator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestTranslation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitTranslation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "translators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyTranslation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyTranslator",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDistributedEvent {
  export type InputTuple = [requestId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [requestId: bigint, amount: bigint];
  export interface OutputObject {
    requestId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TranslationRequestedEvent {
  export type InputTuple = [
    id: BigNumberish,
    requester: AddressLike,
    sourceLang: BigNumberish,
    targetLang: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    requester: string,
    sourceLang: bigint,
    targetLang: bigint
  ];
  export interface OutputObject {
    id: bigint;
    requester: string;
    sourceLang: bigint;
    targetLang: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TranslationSubmittedEvent {
  export type InputTuple = [id: BigNumberish, translator: AddressLike];
  export type OutputTuple = [id: bigint, translator: string];
  export interface OutputObject {
    id: bigint;
    translator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TranslationVerifiedEvent {
  export type InputTuple = [id: BigNumberish, qualityScore: BigNumberish];
  export type OutputTuple = [id: bigint, qualityScore: bigint];
  export interface OutputObject {
    id: bigint;
    qualityScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TranslatorRegisteredEvent {
  export type InputTuple = [translator: AddressLike];
  export type OutputTuple = [translator: string];
  export interface OutputObject {
    translator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface XULTranslator extends BaseContract {
  connect(runner?: ContractRunner | null): XULTranslator;
  waitForDeployment(): Promise<this>;

  interface: XULTranslatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAIModel: TypedContractMethod<
    [name: string, version: string, accuracy: BigNumberish],
    [void],
    "nonpayable"
  >;

  addAIVerifier: TypedContractMethod<
    [verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  aiModels: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        name: string;
        version: string;
        accuracy: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  aiTranslate: TypedContractMethod<
    [
      requestId: BigNumberish,
      translation: string,
      aiProof: BytesLike,
      qualityScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  aiVerifiers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  disputeTranslation: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAIModels: TypedContractMethod<
    [],
    [XULTranslator.AIModelStructOutput[]],
    "view"
  >;

  getLanguageName: TypedContractMethod<[lang: BigNumberish], [string], "view">;

  getRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [XULTranslator.TranslationRequestStructOutput],
    "view"
  >;

  getTranslator: TypedContractMethod<
    [translator: AddressLike],
    [XULTranslator.TranslatorStructOutput],
    "view"
  >;

  minReward: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFee: TypedContractMethod<[], [bigint], "view">;

  registerTranslator: TypedContractMethod<
    [specialties: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestTranslation: TypedContractMethod<
    [
      sourceText: string,
      sourceLang: BigNumberish,
      targetLang: BigNumberish,
      reward: BigNumberish,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  requests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        string
      ] & {
        id: bigint;
        requester: string;
        sourceText: string;
        sourceLang: bigint;
        targetLang: bigint;
        reward: bigint;
        deadline: bigint;
        status: bigint;
        translation: string;
        translator: string;
        qualityScore: bigint;
        aiProof: string;
      }
    ],
    "view"
  >;

  resolveDispute: TypedContractMethod<
    [
      requestId: BigNumberish,
      favorTranslator: boolean,
      translatorShare: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  rewardToken: TypedContractMethod<[], [string], "view">;

  setMinReward: TypedContractMethod<
    [_minReward: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitTranslation: TypedContractMethod<
    [requestId: BigNumberish, translation: string],
    [void],
    "nonpayable"
  >;

  totalVolume: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  translators: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, boolean, boolean] & {
        wallet: string;
        reputation: bigint;
        completedJobs: bigint;
        totalEarned: bigint;
        isVerified: boolean;
        isActive: boolean;
      }
    ],
    "view"
  >;

  verifyTranslation: TypedContractMethod<
    [requestId: BigNumberish, qualityScore: BigNumberish, aiProof: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyTranslator: TypedContractMethod<
    [translator: AddressLike, verified: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAIModel"
  ): TypedContractMethod<
    [name: string, version: string, accuracy: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addAIVerifier"
  ): TypedContractMethod<[verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "aiModels"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        name: string;
        version: string;
        accuracy: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "aiTranslate"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      translation: string,
      aiProof: BytesLike,
      qualityScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "aiVerifiers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "disputeTranslation"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAIModels"
  ): TypedContractMethod<[], [XULTranslator.AIModelStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getLanguageName"
  ): TypedContractMethod<[lang: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [XULTranslator.TranslationRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTranslator"
  ): TypedContractMethod<
    [translator: AddressLike],
    [XULTranslator.TranslatorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "minReward"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerTranslator"
  ): TypedContractMethod<[specialties: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestTranslation"
  ): TypedContractMethod<
    [
      sourceText: string,
      sourceLang: BigNumberish,
      targetLang: BigNumberish,
      reward: BigNumberish,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        string
      ] & {
        id: bigint;
        requester: string;
        sourceText: string;
        sourceLang: bigint;
        targetLang: bigint;
        reward: bigint;
        deadline: bigint;
        status: bigint;
        translation: string;
        translator: string;
        qualityScore: bigint;
        aiProof: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      favorTranslator: boolean,
      translatorShare: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rewardToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setMinReward"
  ): TypedContractMethod<[_minReward: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitTranslation"
  ): TypedContractMethod<
    [requestId: BigNumberish, translation: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalVolume"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "translators"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, boolean, boolean] & {
        wallet: string;
        reputation: bigint;
        completedJobs: bigint;
        totalEarned: bigint;
        isVerified: boolean;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyTranslation"
  ): TypedContractMethod<
    [requestId: BigNumberish, qualityScore: BigNumberish, aiProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyTranslator"
  ): TypedContractMethod<
    [translator: AddressLike, verified: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardDistributed"
  ): TypedContractEvent<
    RewardDistributedEvent.InputTuple,
    RewardDistributedEvent.OutputTuple,
    RewardDistributedEvent.OutputObject
  >;
  getEvent(
    key: "TranslationRequested"
  ): TypedContractEvent<
    TranslationRequestedEvent.InputTuple,
    TranslationRequestedEvent.OutputTuple,
    TranslationRequestedEvent.OutputObject
  >;
  getEvent(
    key: "TranslationSubmitted"
  ): TypedContractEvent<
    TranslationSubmittedEvent.InputTuple,
    TranslationSubmittedEvent.OutputTuple,
    TranslationSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "TranslationVerified"
  ): TypedContractEvent<
    TranslationVerifiedEvent.InputTuple,
    TranslationVerifiedEvent.OutputTuple,
    TranslationVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "TranslatorRegistered"
  ): TypedContractEvent<
    TranslatorRegisteredEvent.InputTuple,
    TranslatorRegisteredEvent.OutputTuple,
    TranslatorRegisteredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardDistributed(uint256,uint256)": TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
    RewardDistributed: TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;

    "TranslationRequested(uint256,address,uint8,uint8)": TypedContractEvent<
      TranslationRequestedEvent.InputTuple,
      TranslationRequestedEvent.OutputTuple,
      TranslationRequestedEvent.OutputObject
    >;
    TranslationRequested: TypedContractEvent<
      TranslationRequestedEvent.InputTuple,
      TranslationRequestedEvent.OutputTuple,
      TranslationRequestedEvent.OutputObject
    >;

    "TranslationSubmitted(uint256,address)": TypedContractEvent<
      TranslationSubmittedEvent.InputTuple,
      TranslationSubmittedEvent.OutputTuple,
      TranslationSubmittedEvent.OutputObject
    >;
    TranslationSubmitted: TypedContractEvent<
      TranslationSubmittedEvent.InputTuple,
      TranslationSubmittedEvent.OutputTuple,
      TranslationSubmittedEvent.OutputObject
    >;

    "TranslationVerified(uint256,uint256)": TypedContractEvent<
      TranslationVerifiedEvent.InputTuple,
      TranslationVerifiedEvent.OutputTuple,
      TranslationVerifiedEvent.OutputObject
    >;
    TranslationVerified: TypedContractEvent<
      TranslationVerifiedEvent.InputTuple,
      TranslationVerifiedEvent.OutputTuple,
      TranslationVerifiedEvent.OutputObject
    >;

    "TranslatorRegistered(address)": TypedContractEvent<
      TranslatorRegisteredEvent.InputTuple,
      TranslatorRegisteredEvent.OutputTuple,
      TranslatorRegisteredEvent.OutputObject
    >;
    TranslatorRegistered: TypedContractEvent<
      TranslatorRegisteredEvent.InputTuple,
      TranslatorRegisteredEvent.OutputTuple,
      TranslatorRegisteredEvent.OutputObject
    >;
  };
}
